### ISSUE TITLE
how to recharge bttc?

### ISSUE THREAD

**Issue by centny** [bittorrent/go-btfs#114]
```.log
Initializing daemon...
go-btfs version: 2.1.1-f76f7e030
Repo version: 10
System version: amd64/linux
Golang version: go1.15.15
Repo location: /root/.btfs
Peer identity: 16Uiu2HAkz2gYZB8XXdma9SJAaJpknZgc9o87MqmEfJxg1iJ3EL6C
the address of Bttc format is:  0xe292823682125E34F0173c72890D455Af17c8Ab4
the address of Tron format is:  TWdDE1djQFd1ST4kmr43nhwx3BBVaTdESH
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xe292823682125e34f0173c72890d455af17c8ab4
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xe292823682125e34f0173c72890d455af17c8ab4
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xe292823682125e34f0173c72890d455af17c8ab4
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xe292823682125e34f0173c72890d455af17c8ab4
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xe292823682125e34f0173c72890d455af17c8ab4
```

* i want to run a BTFS host, follow doc.
* how to recharage the bttc?
* already try withdraw btt to 0xe292823682125E34F0173c72890D455Af17c8Ab4 in Binance
* already try withdraw btt to TWdDE1djQFd1ST4kmr43nhwx3BBVaTdESH in Binance

**Comment by pkyriacou** [comment]
You have:
1. Transferred 193,389 BTT to the BSC (Binance Smart Chain) Network, at address: [0xe292823682125E34F0173c72890D455Af17c8Ab4](https://bscscan.com/address/0xe292823682125E34F0173c72890D455Af17c8Ab4) 
2. Transferred 65,778 BTT to the Tron Network, at address [TWdDE1djQFd1ST4kmr43nhwx3BBVaTdESH](https://tronscan.org/#/address/TWdDE1djQFd1ST4kmr43nhwx3BBVaTdESH)

In order to get these BTT to the BTTC chain, you will need to:
1. Transfer some TRX and BNB to the respective addresses, in order to pay for gas fees. This will allow you to utilize the Tron and BSC networks to send your funds to the BTTC network. 
2. After you have some TRX and BNB for gas fees, use the https://wallet.bt.io/bridge to bridge the BTT tokens from the Tron and BSC networks to the BTTC network. You will need to use MetaMask and TronLink (or similar) wallets to accomplish this.
3. You will need to SWAP your BTT_b (BTT bridged from BSC network) to BTT using https://wallet.bt.io/bttcswap

Refer to this guide: 
Tron to BTTC swap: https://medium.com/@BitTorrent/how-to-swap-trc20-btt-to-brc20-btt-on-bittorrent-chain-15d125d772e0

Note: I needed around 30TRX in order to transfer my BTTOLD to the BTTC network from Tron network.

**Comment by centny** [comment]
@pkyriacou thinks, sloved. the doc should be added the more detail like this.

**Comment by centny** [comment]
@pkyriacou need your help for #117
