### ISSUE TITLE
how to mining?

### ISSUE THREAD

**Issue by centny** [bittorrent/go-btfs#117]
* I need some help, new to btfs, how to mining btt on btfs 2.0? 
* Is there any relevant documentation?  Already follow https://docs.btfs.io/docs, and the daemon is running.
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/4049551/158134521-7a30038b-6f84-4478-a994-d48a6f239f08.png">

question is 
* 1. Is this mining?
* 2. The storage is only 4.00 GiB, my disk free space is 800G+
* 3. i have multi disk, how to add more storage?
* 4. The doc said stake BTT is required. is it I need withdraw more btt? And how to stake it? Keep balance having btt?

**Comment by centny** [comment]
@[pkyriacou](https://github.com/pkyriacou) need you help

**Comment by pkyriacou** [comment]
Hello,

The node is still being introduced to the network. This can take some time, your mileage may vary as to when it is accepted. One of my nodes took 2 weeks, whereas another was accepted in a day. When it is, it will show a score. Your score must be 8 or greater in order to be able to start gaining. Note that BTFS is not really mining per-se like other crypto. You can gain BTTC in 2 ways:
1. Airdrops for running a BTFS host (I have accumulated close to 6M BTTC from airdrops since October 2021 for 1 node)
2. Cheques, which you receive once somebody rents your storage, that you can then cash out for WBTT, which can be converted to BTT. These will slowly trickle in as you get contracts as people rent the storage you provide.

Please make sure to run the below in order to configure your node as a host, which will allow you to earn BTTC:
`btfs config profile apply storage-host`

To expand the storage size you can use the command:
`btfs storage announce --host-storage-max=<size in gigabytes to allocate>`

You can see more info on running a BTFS Host here: https://docs.btfs.io/docs/run-a-btfs-host-1

I am not one of the developers but from experience, it seems that btfs defaults to the size of the partition on which it's $BTFS_PATH is set **(maybe this needs to be clarified by the devs!!)**. i.e. If you set max storage to 800GB but your $BTFS_PATH is set to a partition which has only 4GB in size, it will reset itself to 4GB max storage. Please see here on how to change hosting folder: https://docs.btfs.io/docs/change-my-hosting-folder-1

**Comment by centny** [comment]
@pkyriacou thinks
`btfs config profile apply storage-host` command is not supported

**Comment by Sophia-yu-kk** [comment]
The stake feature is not yet live, and stake are not currently required for consideration.
