### ISSUE TITLE
Vault Address

### ISSUE THREAD

**Issue by chris110110** [bittorrent/go-btfs#163]
Hello, I get a new error with Vault Address,

Terminal shows:
init settlement err:  init vault service: vault init: execution reverted: vault alerady created

Error: init vault service: vault init: execution reverted: vault alerady created

Please help me.
What can I do?
Thanks.
Peer: 16Uiu2HAmSdmJd3T8dm7JyW1bG22xbsJgHSJLJ3f4DJiMxZ6tH3dV

**Comment by Robin-Luooo** [comment]
This error means your have already deployed the new version Vault, however I found it haven't by calling the VaultFactory's peerVaultAddress function.

I guess your host id is not 16Uiu2HAmSdmJd3T8dm7JyW1bG22xbsJgHSJLJ3f4DJiMxZ6tH3dV, or something goes wrong. Please use the following command to confirm your host id:

`btfs id | grep ID`

**Comment by chris110110** [comment]
Hi Robin,
thanks for your answer.
btfs id | grep ID give me this:

btfs id | grep ID
	"ID": "16Uiu2HAmSdmJd3T8dm7JyW1bG22xbsJgHSJLJ3f4DJiMxZ6tH3dV",
	"DaemonProcessID": -1,
	"ChainID": 0

Thank you in advance.
Regards,
Chris

**Comment by Robin-Luooo** [comment]
Hi @chris110110 

It seems your host id is right, and I can't find the reason why now. And I need the following information to figure it out:

1. It seems you are using the v2.1.2 go-btfs, and want to do upgradation. Did your run command `btfs daemon --chain-id 199`  ? You can refer to the [upgrade tutorial](https://docs.btfs.io/docs/tutorials-for-upgrading-to-v212) for details.
2. Please provide all logs shown on terminal while you run `btfs daemon --chain-id 199`. Please hide private info like private key.

Thanks and Regards
Robin

**Comment by chris110110** [comment]
Hi Robin,
first, thank you for your efforts.

Here the informations what you asked.

----------------------------------------------------------------
btfs daemon --chain-id 199
Initializing daemon...
go-btfs version: 2.1.2-834fd1b
Repo version: 10
System version: arm/linux
Golang version: go1.15.15
Repo location: /media/pi/BTFSDRIVE/btfs
Peer identity: 16Uiu2HAmSdmJd3T8dm7JyW1bG22xbsJgHSJLJ3f4DJiMxZ6tH3dV
the address of Bttc format is:  0x4d9F486916C16C91561bC0d448A6E629c11d296C
the address of Tron format is:  TH3dqzkuESGEvhwUvNZY4URVisdPq9J4QF
init settlement err:  init vault service: vault init: execution reverted: vault alerady created

Error: init vault service: vault init: execution reverted: vault alerady created
----------------------------------------------------------------

Thanks and Regards
Chris

**Comment by Robin-Luooo** [comment]
Hi @chris110110 

Thanks chris, it seems that your go-btfs daemon didn't execute the upgradation flow as expected. I need your VaultFactory address pls.

1. Go to your $BTFS path (namely `/media/pi/BTFSDRIVE/btfs` for you), and run `grep Factory config`
2. Go to your go-btfs source code folder (it seems your compiled by yourself), and run `grep bttcFactoryAddress -R chain/`

Please feedback me the output, thanks

Regards
Robin

**Comment by chris110110** [comment]
Hi Robin,

--------------------------------------------------

1.
grep Factory config
    "CurrentFactory": "0x763d7858287B9a33F4bE5bb3df0241dACc59BCc7",

2.
-this is not working.
-I did not compiled myself. I only use the file from git.

---------------------------------------------

Kind Regards,
Chris

**Comment by Robin-Luooo** [comment]
Hi @chris110110 

The VaultFactory address in your config file is the newest version Factory. This means the upgrade preparation had done while you run `btfs daemon --chain-id 199` at first time, however the upgradation failed.

You can modify the `CurrentFactory`'s value to old version, namely "0x9AF4bEc1A30BeC47756Ecef4cf43B91592121bC9", and then try running `btfs daemon --chain-id 199` again. Let me know the output logs, thanks~

Kind Regards
Robin

**Comment by Robin-Luooo** [comment]
Hi @chris110110 

I just found the main reason, because the block that containing your deploy-vault-transaction is in `pending` status. This maybe happen when the block isn't mined by any miner. The transaction will expired in 2 hours by default, which can be changed by the miner itself. 

Your can view the transaction's status in https://bttcscan.com/tx/0xc2e685918488ac8e5f6ad04cc5d75c2104bcd2b227f4b6953263822980ec8a13

Let's wait for another several hours. After the transaction expired, you can try again.

Thanks for your patience
Robin

**Comment by chris110110** [comment]
Hi Robin,
Ok i try in a view hours again.
Should i set the Address in config back or only start the deamon?

Thanks for all.

Regards,
Chris

**Comment by Robin-Luooo** [comment]
Hi @chris110110 

As mentioned above, your deploy-vault-transaction is still pending now, https://bttcscan.com/tx/0xc2e685918488ac8e5f6ad04cc5d75c2104bcd2b227f4b6953263822980ec8a13.

And I also found [another two transactions in pending status](https://bttcscan.com/address/0x4d9f486916c16c91561bc0d448a6e629c11d296c) in your account. What's interesting is that you transferred 0 btt to yourself at a very low gas price(0.00000000121 BTT) in this [transaction](https://bttcscan.com/tx/0x938ba615f809cbd1e03bd3d36ee513ffe207854d0461eeea82f580248da12a26); This gas price is too much low than a normal price, e.g. 0.0003 BTT, and it causes that no miner glad to mine this block, and it blocks the following two transactions, too.

Did you transferred to yourself using the Metamask? You can check your transactions inner your Metamask's Activity tab (note switch to BTTC network)，I guess it still in pending status. You can **Cancel** or **Speed Up** the transaction by upper the **gas price** to a normal value, e.g. 300000.

After you do this, the following two pending transactions (including the deploy-vault-transaction) in your account will finish as expected. Then you can run `btfs daemon --chain-id 199` to restart your btfs node. This should go well, because your vault should have been deployed.

Have a try, glad to hear your feedback if anything goes wrong.

Regards,
Robin

**Comment by chris110110** [comment]
Hi Robin,

I was able to cancle one transaction and this is the only one which is shown in MetaMask.
The transfer of 0BTT was show up when you want to cancle a transaction in MetaMask, I dont know why.
However, this was the only one what I can see in MetaMask.
Is there an other way to cancle the other two transactions?

Thank you very much for your help.

Regards,
Chris

**Comment by Robin-Luooo** [comment]
Hi @chris110110 

Because the other two pending orders are made by the go-btfs, so it's a little tricky to cancel them in Metamask.

1. Go to Metamask's **Settings > Advanced** page, open the **Customize transaction nonce** option.
2. You need to run two new transactions in Metamasks to override the two pending transactions.
2.1 Make sure your two pending transactions' nonce is [`3`](https://bttcscan.com/tx/0x3fb3e9ca217f27e2906621b73f934921a2a2b83938ea8229cf03b75b9a12507e) and [`4`](https://bttcscan.com/tx/0xc2e685918488ac8e5f6ad04cc5d75c2104bcd2b227f4b6953263822980ec8a13);
2.2 Run 1st transaction to override the `nonce=3` transaction: just transfer some BTT to another BTTC address(or just to yourself), and specify `CUSTOM NONCE = 3` before **Confirm**. This transaction will override the `nonce=3` pending transaction.
2.3 Then go to the [nonce=3 pending transaction page](https://bttcscan.com/tx/0x3fb3e9ca217f27e2906621b73f934921a2a2b83938ea8229cf03b75b9a12507e), make sure it has been cancelled.
2.4 Repeat 2.2 step, and specify `CUSTOM NONCE = 4` to override another [`nonce=4` pending transaction](https://bttcscan.com/tx/0xc2e685918488ac8e5f6ad04cc5d75c2104bcd2b227f4b6953263822980ec8a13).

Have a try~

Regards,
Robin

**Comment by chris110110** [comment]
Hi Robin,
I try as  soon as possible and let you know.
Thank you very much.
Regards,
Chris

**Comment by chris110110** [comment]
Hi Robin,

thank you very much for your help, you are the best.
Your method to override the pending transactions worked very well.
The deamon is starting correct and is running now.

This complete process was very instructive for me.
In future i think i know what to do and i understood where the problem was.

Thank you very much again.
Have a good weekend.

Kind regards,
Chris
