### ISSUE TITLE
BTFS ERROR HELP!

### ISSUE THREAD

**Issue by ROG707** [bittorrent/go-btfs#332]
2023-06-26T18:04:47.730+0900    [31mERROR[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode
2023-06-26T18:04:47.730+0900    [31mERROR[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode

BTFS 2.3.2

Even after updating, the error message is displayed continuously. help ME!!.

**Comment by CrCati** [comment]
Hi, @ROG707, could you please share more information  about the environmental details and the steps to reproduce this error.

**To Reproduce**
Steps to reproduce the behavior:

    Execute command '....'
    See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop** (please complete the following information):

    OS: [e.g. Ubuntu 22.04]
    Version [e.g. 2.2.1]

**Additional context**
Add any other context about the problem here.

**Comment by CrCati** [comment]
Hi, @ROG707; thank you for your feedback. I have contacted the community developer regarding the issue, and it is a known issue related to upstream issues. Once it is fixed, we will merge it. Currently, you can ignore it.
