### ISSUE TITLE
[BUG] GitHub Integration / App authentication fails with error

### ISSUE THREAD

**Issue by oldcityws** [bittorrent/go-btfs#334]
**Describe the bug**
BTFS3 app integrated with GitHub will not allow authorization, produces an error when I click through after selecting a repo .

**To Reproduce**
1.  Try to integrate by authorizing a repo 
2.  Click through to go to authorization

**Expected behavior**
I expect to authorize / connect with BTFS3 app

**Screenshots**
![image](https://github.com/bittorrent/go-btfs/assets/42473932/a01b6cd7-9f00-47bb-85e5-c2bff8229639)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10

**Additional context**
Chrome Browser

**Comment by CrCati** [comment]
Hi, @oldcityws, That response may be caused by an invalid storage3 cookie. Please refresh your page and log in to storage3, then try to deploy your selected repo again. I just tried with a new GitHub account, and deploying a selected repo was successful. BTW, you can discuss storage3 issues in the discord community instead of this go-btfs github repo: https://discord.com/invite/VmMjp2gvAB
