### ISSUE TITLE
[QUESTION] How to extend the storage duration of an uploaded file

### ISSUE THREAD

**Issue by pbtrung** [bittorrent/go-btfs#344]
After uploading a file to BTFS and deleting the local ipfs file store, how do I renew/extend the storage duration of that file? The obvious way is to download and then upload it again. Is it possible to do that on chain (no local storage)? Thanks.

**Comment by simbadMarino** [comment]
Hey there, as far as I know the only way to "extend" the duration of a file is to use btns instead of btfs only, but this method requires you to upload again but you keep using the same btns key. I documented the process here: https://www.cctechmx.org/btfs_docs/common_usage#publishing-to-bittorrent-name-system-btns

If there is a newly introduced method to do this on without managing the file would be great as well :)

**Comment by CrCati** [comment]
Hi, @pbtrung; currently, there is no command to renew/extend the storage duration of the file. Downloading and uploading the file again is the way to extend the time.

**Comment by pbtrung** [comment]
Thanks. Will closed this as solved.
