### ISSUE TITLE
go-btfs high RAM usege

### ISSUE THREAD

**Issue by dipol0** [bittorrent/go-btfs#396]
go-btfs high ram usage after ~8 days uptime. When node start btfs daemon use ~1.3Gb ram. After 8 days uptime ram usage up to 3+Gb. **Its normal ?**

docker --version
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

go-btfs - 2.3.3

![Выделение_233](https://github.com/bittorrent/go-btfs/assets/32021806/71d49948-07c2-49f9-9156-00b1a539e822)
![mc  manager@cloud :~_001](https://github.com/bittorrent/go-btfs/assets/32021806/447a647f-af64-42aa-be3a-3cdab313e698)

Restart...

![Выделение_234](https://github.com/bittorrent/go-btfs/assets/32021806/5501bcec-6166-4588-b370-78f03b9a57ad)
![manager@cloud: ~_001](https://github.com/bittorrent/go-btfs/assets/32021806/42ea35d7-e98d-402d-9750-fc2cb4fc79f8)

**Comment by yu-btc** [comment]
The BTFS technical community has noted your question and will feedback the results after troubleshooting. Thank you for your question.

**Comment by yu-btc** [comment]
After the BTFS node daemon is turned on, it is normal for the memory footprint to increase. This is because BTFS nodes need to load and process large amounts of data blocks and index information, as well as maintain the state of network connections and interactions. As the node is involved in more data transfer and storage tasks, the memory footprint will gradually increase.Referring to the data information you provided, your node situation is normal, please do not worry.

**Comment by simbadMarino** [comment]
Is it possible to somehow purge unused RAM memory to reduce resource usage in IOT devices? IOT devices like raspberry pi (which is great for home usage due to low power consumption) have shown great advantages as host devices and having a constant 3 to 4 GB memory consumption increases the cost of the device considerably.

BTFS promise is to run even on a 1GB RAM device. If there is a technical constrain to keep this requirement with the latest updates please consider updating the documentation :), if an improvement on performance is feasible please consider implementing it on next release as priority. 

Again, being able to keep BTFS resources consumption such as CPU & RAM as low as possible increases the possibility of people to have a node at home, thus increasing decentralization of nodes.

Thank you!

**Comment by yu-btc** [comment]
> Is it possible to somehow purge unused RAM memory to reduce resource usage in IOT devices? IOT devices like raspberry pi (which is great for home usage due to low power consumption) have shown great advantages as host devices and having a constant 3 to 4 GB memory consumption increases the cost of the device considerably.
> 
> BTFS promise is to run even on a 1GB RAM device. If there is a technical constrain to keep this requirement with the latest updates please consider updating the documentation :), if an improvement on performance is feasible please consider implementing it on next release as priority.
> 
> Again, being able to keep BTFS resources consumption such as CPU & RAM as low as possible increases the possibility of people to have a node at home, thus increasing decentralization of nodes.
> 
> Thank you!

Reducing node RAM usage requires optimisation of the code and associated algorithms, including work on reducing memory leaks and unnecessary variable occupation. These efforts have already been optimised in v2.3.0, and the BTFS technical community will continue to work on these optimisations to meet node requirements.

Thank you for your suggestions and have a great day.

**Comment by simbadMarino** [comment]
Thank you for the feedback. Have a great day too!
