### ISSUE TITLE
File upload to BTFS says - failed to find more valid hosts, please try again later

### ISSUE THREAD

**Issue by satish4cs** [bittorrent/go-btfs#57]
I am able to add a file to my local node using the 'btfs add' command and when I try to upload to the btfs network using the upload command and check the status, it is saying as below

{"Status":"error","Message":"**failed to find more valid hosts, please try again later**","AdditionalInfo":"","FileHash":"QmNrAQFXo7RFW5xiGLmeN6XXXXXXXXXXXXXXXXXX","Shards":{"c937138a-XXXX-421e-b9fd-e667653c1a61:QmNrAQFXo7RFW5xiGLmeN6XXXXXXXXXXXXXXXXXX:0":{"ContractID":"","Price":0,"Host":"","Status":"init","Message":"","AdditionalInfo":""}}}

Below are some screenshots:

Upload screenshot:

![image](https://user-images.githubusercontent.com/13938447/153771302-453ae056-904c-4ac0-ba82-66420850d7bc.png)

**Node sync & copy log:**
![image](https://user-images.githubusercontent.com/13938447/153771457-e13c6c37-ba45-4d73-83b6-05d23c274b26.png)

Dashboard: **It may take few days to show the node online and uptime % as per previous issue comments**

![image](https://user-images.githubusercontent.com/13938447/153771200-cb2d0953-18c0-4d3a-84a2-db3cd01f90e8.png)

**Comment by simbadMarino** [comment]
Happening to me as well, it was working properly some days ago and now just throws the same error. Anyone with the same issue?

**Comment by Sophia-yu-kk** [comment]
Please provide us with your version number，If it is not the latest version, we suggest you upgrade to the latest version.

**Comment by satish4cs** [comment]
I believe its the latest version of BTFS.
![image](https://user-images.githubusercontent.com/13938447/153828693-d974e1e8-2b79-4234-8093-42ef5879e99f.png)

**Comment by Sophia-yu-kk** [comment]
./btfs init -p storage-host-testnet

Need init node to testnet environment.

**Comment by satish4cs** [comment]
Same result  - failed to find more valid hosts, please try again later

Am I missing the flow of commands?

btfs init -p storage-host-testnet
btfs config profile apply storage-client-testnet
btfs config profile apply storage-host-testnet
btfs daemon

**Comment by simbadMarino** [comment]
@satish4cs , looks like something in the repo is getting corrupted by applying the:
` btfs config profile apply storage-client-testnet` and/or  `btfs config profile apply storage-host-testnet`

I had to remove my repo and start over again. I can confirm the following procedure flow works:

1. btfs init -p storage-host-testnet
2. btfs daemon --chain-id 1029 --> Proceed to Send your testnet tokens in this step
3. Upload your files using dCloud GUI or BTFS CLI.

Give it a try and let us know if it works :) 

@Sophia-yu-kk , I'll try to reproduce the issue again to identify what's causing the repo to fail but will wait until mainnet to launch to verify the issue is still there.

**Comment by satish4cs** [comment]
Yes, it is working now with these commands.

btfs init -p storage-host-testnet 
btfs daemon --chain-id 1029 [ AddBTT to the address & WBTT to vault at this point]
